// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY802kB8_K5LYDO11udnU5_oG4l3TXWAU',
    appId: '1:746713602476:web:084c4eabf97608239f0209',
    messagingSenderId: '746713602476',
    projectId: 'totalx-1af71',
    authDomain: 'totalx-1af71.firebaseapp.com',
    storageBucket: 'totalx-1af71.firebasestorage.app',
    measurementId: 'G-W11LGDZFVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0iW9WBCC74duoYhT8jCiDBTT4xsH3PaA',
    appId: '1:746713602476:android:ffafed663b7045159f0209',
    messagingSenderId: '746713602476',
    projectId: 'totalx-1af71',
    storageBucket: 'totalx-1af71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA42wpMe3c9NrnEHA71HbjMuGUowLHLZaI',
    appId: '1:746713602476:ios:060bb89b584fa9ef9f0209',
    messagingSenderId: '746713602476',
    projectId: 'totalx-1af71',
    storageBucket: 'totalx-1af71.firebasestorage.app',
    iosBundleId: 'com.example.totalx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA42wpMe3c9NrnEHA71HbjMuGUowLHLZaI',
    appId: '1:746713602476:ios:060bb89b584fa9ef9f0209',
    messagingSenderId: '746713602476',
    projectId: 'totalx-1af71',
    storageBucket: 'totalx-1af71.firebasestorage.app',
    iosBundleId: 'com.example.totalx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY802kB8_K5LYDO11udnU5_oG4l3TXWAU',
    appId: '1:746713602476:web:b7bb7fbcb0d6e7929f0209',
    messagingSenderId: '746713602476',
    projectId: 'totalx-1af71',
    authDomain: 'totalx-1af71.firebaseapp.com',
    storageBucket: 'totalx-1af71.firebasestorage.app',
    measurementId: 'G-3CZ349S657',
  );
}
